name: Run DFA Minimizer Tests

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/tests.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install build essentials
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build dfa_minimizer using build.sh
        run: bash backend/build.sh

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          pytest backend/tests.py
