name: Run DFA Minimizer Tests

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/tests.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/tests.yml'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools and nlohmann-json
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y clang build-essential nlohmann-json3-dev
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew update
            brew install llvm nlohmann-json
            brew link --force llvm
          fi

      - name: Build dfa_minimizer using build.sh
        working-directory: backend
        run: bash build.sh

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          pytest backend/tests.py
